#define GRAVEDAD 9.8
#define WIN_ANCHO 800
#define WIN_ALTO 600
#define PI 3.1415
#define ORIGEN_Y 200
#define MAX_OBJETOS 3
#define MAX_OBJETOS_INICIAL 3
#define BOMBA_SONIDO "Sonidos/Explosion.wav"
#define FRUTA_SONIDO "Sonidos/Choque.wav"
#define MUSICA_FONDO "Sonidos/fondo.wav"
#define MIN_Z -500
#define MAX_Z 500
